/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chats;

import static chats.chatClient.dos;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.net.Socket;

/**
 *
 * @author Hachem
 */
public class chatServer extends javax.swing.JFrame {

    static ServerSocket ss;
    static Socket s;
    static DataInputStream dis;
    static DataOutputStream dos;
   
    public chatServer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        a = new javax.swing.JTextArea();
        c = new javax.swing.JTextField();
        b = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(null);

        a.setColumns(20);
        a.setRows(5);
        jScrollPane1.setViewportView(a);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 20, 360, 230);
        getContentPane().add(c);
        c.setBounds(20, 260, 270, 30);

        b.setText("envoyer");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        getContentPane().add(b);
        b.setBounds(300, 260, 79, 26);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
    
        try
        {
            //System.out.println("client :");
            //System.out.println(InetAddress.getLocalHost().getHostAddress());
            //System.out.println(InetAddress.getLocalHost().getHostName());
        String msgout="";
        msgout=c.getText().trim();
        dos.writeUTF(msgout);
        dos.writeUTF(InetAddress.getLocalHost().getHostAddress());
        dos.writeUTF(InetAddress.getLocalHost().getHostName());
        }
        catch(Exception e)
        {
        
        }
            
    }//GEN-LAST:event_bActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
                new chatServer().setVisible(true);
        
       String msgin="";
        try
        {
        ss=new ServerSocket(1201);
        s=ss.accept();
        dis=new DataInputStream(s.getInputStream());
        dos = new DataOutputStream(s.getOutputStream());
            while (!msgin.equals("exit")) 
            {
                msgin=dis.readUTF();
                
                a.setText(a.getText().trim()+"\n"+msgin);
            }
        }
        catch(Exception e)
        {
         System.out.println("ff");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    static javax.swing.JTextArea a;
    private javax.swing.JButton b;
    private javax.swing.JTextField c;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
